export const cuisineList = [
  "Đậu phụ sốt cà chua",
  "Phở chay",
  "Gỏi cuốn chay",
  "Canh chua chay",
  "Cafe",
  "Cơm chiên chay",
  "Lẩu chay",
  "Bánh xèo chay",
  "Nem chay",
  "Sushi chay",
  "Đậu hũ kho nấm",
  "Bún riêu chay",
  "Miến xào chay",
  "Cháo nấm chay",
  "Bánh khọt chay",
  "Cà tím kho tộ",
  "Salad trộn chay",
  "Bánh cuốn chay",
  "Rau củ chiên giòn",
  "Đậu hũ chiên sả ớt",
  "Đậu hũ chiên sả ớt",
  "Mì Quảng chay",
];
